const FirstBlogPost = () => {
  return (
    <div>
      <h1 className="font-bold text-3xl text-center mb-2">20th December 2024</h1>
      <p className="text-center px-4">Over the last few months of my career I've been wanting to learn more dev skills to transition from a tester into a dev.</p>
      <p className="text-center px-4 mb-4">This is the first post going through the initial setup of the JSON Puncheon site and next steps.</p>
      <h2 className="font-bold text-2xl text-center mb-2">Background & Initial Site Setup</h2>
      <p className="text-center px-4 mb-2">I am a senior software tester who has been working in the tech industry for a decade. I have had an interest in programming but have never been able to get any longevity in learning.</p>
      <p className="text-center px-4 mb-2">On the 30th of November I did some thinking and decided to try kickstart my journey with the most generic of first forays into programming, a blog. The intention was for me to use my interest in football as a way to fuel my desire to learn programming.</p>
      <p className="text-center px-4 mb-2">I decided I wanted to make use of React, Tailwind and Typescript, as these are pretty industry standard and I'd used all 3 in my work prior.</p>
      <p className="text-center px-4 mb-2">On the 13th of December I first started making the blog using create-react-app following <a target="_blank" className="text-blue-600" href="https://www.geeksforgeeks.org/blog-page-template-using-reactjs-and-tailwind/">this tutorial</a>. I realised that tutorial was shorter than I wanted it to be so had another look around for different content and found <a target="_blank" className="text-blue-600" href="https://www.youtube.com/watch?v=siTUv1L9ymM">this YouTube tutorial</a> which guided you through setting up a ToDo List.</p>
      <p className="text-center px-4 mb-2">This tutorial used React, Tailwind and Vite and helped a lot in getting my head around hooks, components and state in React. I got the app deploying via Github Pages.</p>
      <p className="text-center px-4 mb-2">I finished with the tutorial today, on 20th of December and once I was finished I pulled that code out into its own repo <a target="_blank" className="text-blue-600" href="https://github.com/raysmith745/toDoList">here</a>. It is currently available in the nav bar of this site. I imagine at some point soon I'll remove the ToDo List from this site altogether as it doesn't fit here at all, but for now it is proving useful as a nice reference to help me use React in other football related content.</p>
      <p className="text-center px-4 mb-2">Since then I have carried on updating the JSON Puncheon site, trying to make it more into a blog and getting a decent base down before I start with other apps linking off from this hub.</p>
      <p className="text-center px-4 mb-2">I started by adding a header to the site using the following tutorials <a target="_blank" className="text-blue-600" href="https://www.dhiwise.com/post/building-a-react-header-a-step-by-step-guide">here</a> and <a target="_blank" className="text-blue-600" href="https://medium.com/@dimterion/simple-responsive-header-with-react-tailwind-css-803fe63ecda9">here</a>.</p>
      <p className="text-center px-4 mb-2">Then I added separate pages to the site. I pulled out the ToDo List into /to-do-list as it was a weird thing to have on a homepage. I created a HomePage.tsx for the actual homepage. Then created a /how-many-michus page which i'll explain after in the Next Steps section. I used <a target="_blank" className="text-blue-600" href="https://www.npmjs.com/package/react-router-dom">react-router-dom</a> to tie this all together. All I used to do this was pinging questions to ChatGPT and using the output to guide me through the process, but without mindless copy & pasting.</p>
      <p className="text-center px-4 mb-4">Finally, I added this first blog post under /blog-posts/24-12-20-post.tsx and created a summary on the homepage linking through to the post. Which brings us right up to here and now.</p>
      <h2 className="font-bold text-2xl text-center mb-2">Next Steps</h2>
      <p className="text-center px-4 mb-2">As of now I have a few ideas for making the blog itself better, and then a load of ideas for football related content in various difficulties.</p>
      <p className="text-center px-4 mb-2">Blog wise, first of all would like to add a footer to get the final bit of initial sheen on the site. After that I think I'm happy with the visuals. I would like to add a dark mode toggle as that feels like a nice little thing to learn and the white background on this page is already hurting my eyes from staring at it while writing code.</p>
      <p className="text-center px-4 mb-2">As I mentioned with the blog posts themselves, currently I'm just adding paragraph tags into the homepage with dates and a summary on, and then a link to a different page with additional content on. So I want to get these better. I guess eventually these could be stored in a database somewhere? Probably overkill but would be a good way to get knowledge around linking up with external services and would force me to take the site off of GitHub Pages and handle my own hosting, deployment, etc.</p>
      <p className="text-center px-4 mb-2">Regarding the How Many Michus page. This was an <a target="_blank" className="text-blue-600" href="https://github.com/raysmith745/how_many_michus">old repo</a> I made 6 years ago when I was first trying to do programming before I'd used React or Tailwind or any of those nice JS packages that make front-end work easier. It put me off doing any front-end development for a long time as I hated trying to figure out CSS. It was my first attempt at combining football and software dev, basically was just an input field where you put a number in and it tells you how many Michus you could have bought for that price. The plan now is to make a new version of that old site and have it on the /how-many-michus page. Working with React on the ToDo List has already made me realise this would be a lot easier than last time.</p>
      <p className="text-center px-4 mb-2">Finally, in future I will want to start adding more football related little ideas. Team creator. Trivia questions linked up to an API or scraping a site for scoring stats etc. Name the last 10 winners of a competition in order. A quiz where it pulls a random PL player and uses their clubs to plot geolocations on a map. Analysing stats and data visualisations. There are millions of possibilities where football is concerned.</p>
      <p className="text-center px-4 mb-2">Hopefully as I develop my skills further I can continue putting them to good use making ever more complicated software with a football focus.</p>
      <p className="text-center px-4">Thanks,</p>
      <p className="text-center px-4">Ray Smith</p>
      <p className="text-center px-4 mb-2">YNWA</p>
    </div>
  );
};

export default FirstBlogPost;
